config/routes.rb
ShelterMe::Application.routes.draw do

  get "messages/new"
  get "journals/new"
  get "pet_videos/new"
  get "pet_photos/new"
  get "shelter_admins/new"
  get "favorites/new"
  get "bonds/new"
  get "addresses/new"
  get "password_resets/new"

  resources :users do
    member do
      get :following, :followers
      get :watching
      get :boosting
      get :managing
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy, :index]
  resources :relationships, only: [:create, :destroy]
  resources :password_resets
  resources :pet_photos
  resources :pet_videos
  resources :pets, except: [:create, :new, :show, :edit, :destroy]
  resources :messages, only: [:new, :create]

  resources :bonds, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :shelter_admins, only: [:create, :destroy]
  resources :breeds
  resources :searches

  root to: 'static_pages#home'
  
  match '/addphoto',          to: 'pet_photos#new'
  match '/pp',                to: 'pet_photos#index'
  
  match '/addvideo',          to: 'pet_videos#new'
  match '/pv',                to: 'pet_videos#index'
  
  match '/pc',                to: 'microposts#index'
  
  match '/s',                 to: 'shelters#index'
  match '/newshelter',        to: 'shelters#new'
  match '/findshelter',       to: 'shelters#find'
  match '/listshelters',      to: 'shelters#list'
  match '/mymanagedpets',     to: 'shelters#managed'
  match '/mmp',               to: 'shelters#managed'
  match '/:shelter_id/featured', to: 'shelters#featured'
  
  match '/p',                 to: 'pets#index'
  match '/addpet',            to: 'pets#addpet'
  match '/newpet',            to: 'pets#new'
  match '/potd',              to: 'pets#potd'
  match '/la',                to: 'pets#potd'
  
  match '/findpet',           to: 'searches#new'
  
  match '/signin',            to: 'sessions#new'
  match '/signout',           to: 'sessions#destroy', via: :delete
  
  match '/join',              to: 'users#new'
  match '/matchme',           to: 'users#matchme'
  match '/u',                 to: 'users#index'
  match '/users',             to: 'users#index'
  match '/u/:id',             to: 'users#show'
  match '/mysponsoredpets',   to: 'users#sponsored'
  match '/msp',               to: 'users#sponsored'
  match '/myfollowedpets',    to: 'users#followed'
  match '/mfp',               to: 'users#followed'
  match '/myupdates',         to: 'users#activity'
  match '/mu',                to: 'users#activity'
  match '/myfollowedusers',   to: 'users#relationships'
  match '/mfu',               to: 'users#relationships'
  match '/myphotos',          to: 'users#photos'
  match '/mp',                to: 'users#photos'
  match '/myvideos',          to: 'users#videos'
  match '/mv',                to: 'users#videos'
  match '/sm',                to: 'users#managers'
  match '/shelter_admins',    to: 'users#managers'
  
  match '/contact',           to: 'messages#new'
  match '/about',             to: 'static_pages#about'
  match '/faq',               to: 'static_pages#faq'
  match '/terms',             to: 'static_pages#terms'
  match '/privacy',           to: 'static_pages#privacy'
  match '/statistics',        to: 'static_pages#statistics'
  match '/tutorial',          to: 'static_pages#tutorial'
  match '/mobile',            to: 'static_pages#home'
  match '/events',            to: 'static_pages#events'
  match '/events_8_9',        to: 'static_pages#events_8_9'
  match '/events_8_10',       to: 'static_pages#events_8_10'

  resources :shelters, path: "", except: [:create, :new, :index, :download]
  resources :shelters, only: [:create, :new, :show, :edit, :destroy]
  resources :shelters, path: "", only: [] do
    resources :pets, path: "", only: [:create, :new, :show, :edit, :destroy]
  end
  
  match '/:shelter_id/*a',    to: "application#routing_error"
  match "*a",                 to: "application#routing_error"
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    respond_to do |format|
      format.html {
        require 'open-uri'
        require 'nokogiri'
        
        # TEMPORARY HACK TO ADD A SPECIFIC PET TO LIST
        # force_pet = Pet.where('slug iLIKE ?', "Nala4").where(pet_state_id: 1).first
        
        if cookies[:featured_pets] && cookies[:featured_shelter] && cookies[:featured_shelter_pets]
          @featured_pets = cookies[:featured_pets].split("&").map{|p| p.to_i}.map{|p| Pet.includes(:pet_state, :gender, :size, :species, :fur_length, :energy_level, :nature, :affection, :secondary_breed, :primary_breed, :age_period, :shelter, :primary_color, :secondary_color).where(id: p, pet_state_id: 1)}.flatten
          
          # TEMPORARY HACK TO ADD A SPECIFIC PET TO LIST
          # if force_pet
          #   @featured_pets = @featured_pets.select{|p| p != force_pet}.sample(3).unshift(force_pet)
          # end
          
          @shelter = Shelter.where(id: cookies[:featured_shelter].to_i).first
          @shelter_pets = cookies[:featured_shelter_pets].split("&").map{|p| p.to_i}.map{|p| Pet.includes(:pet_state, :gender, :size, :species, :fur_length, :energy_level, :nature, :affection, :secondary_breed, :primary_breed, :age_period, :shelter, :primary_color, :secondary_color).where(id: p, pet_state_id: 1)}.flatten

        else  
          #
          # Set location in a cascade from most specific to least.
          # If option doesn't exist, or if validation of it fails, then move to next.
          # 1) value from location cookie
          # 2) current user location
          # 3) geocoder remote ip lookup
          # 4) failure handling of "mapquest not responding"
          #
          @location = "MapQuest not responding"
          if cookies[:location]
            @location = cookies[:location]
          end
          if (validate_location(@current_location) == false) && (signed_in? and current_user.location?)
            @location = current_user.location
          end
          if validate_location(@location) == false  
            s = Geocoder.search(remote_ip)
            @location = s[0].city + ", " + s[0].state_code
          end
          cookies[:location] = @location
          # added + ", US" as hack around Geonames location conflation issues with Canada & California
          shelters = Shelter.near(@location + ", US", 20, order: "distance")
          unless shelters.size > 0
            shelters = Shelter.near(@location + ", US", 100, order: "distance")
          end
          nearbys = shelters.map{|s| s.id}
          if @location != "MapQuest not responding" && nearbys.present?
            @pets = Pet.includes(:pet_state, :gender, :size, :species, :fur_length, :energy_level, :nature, :affection, :secondary_breed, :primary_breed, :age_period, :shelter, :primary_color, :secondary_color)
            @pets = @pets.where('shelter_id in (?)', nearbys).where(pet_state_id: 1).where('pet_photos_count > 0') # Don't show any pets without photos
            if @pets.size > 0
              @featured_pets = @pets.includes(:pet_state).sample(12)
            
              # TEMPORARY HACK TO ADD A SPECIFIC PET TO LIST
              # if force_pet
              #   @featured_pets = @featured_pets.select{|p| p != force_pet}.sample(3).unshift(force_pet)
              # end
            
              @shelter = Shelter.find(@pets.includes(:pet_state).map{|sh| sh.shelter_id}.sample)
              @shelter_pets = @shelter.available.sample(12)
              # Add cache support for featured shelter across the site - and calculate once per day per location (if possible)
              cookies[:featured_pets] = { value: @featured_pets.map{|p| p.id}, expires: 1.day.from_now }
              cookies[:featured_shelter] = { value: @shelter.id, expires: 1.day.from_now }
              cookies[:featured_shelter_pets] = { value: @shelter_pets.map{|p| p.id}, expires: 1.day.from_now}
            else
              @featured_pets = []
              @shelter_pets = []
              @shelter = shelters.first
              flash[:notice] = "Unable to find any pets near #{@location}."
            end
          else
            @featured_pets = []
            @shelter = []
            flash[:notice] = "Unable to find any shelters near #{@location}."
          end
        end
        # TEMPORARY HACK IN LIEU OF ASYNCHRONOUS LOADING & MEMCACHING OF BLOG CONTENT
        #@blog = true
        #blog = Nokogiri::XML(open("http://blog.shelterme.com/feed", read_timeout: 0.5))
        #if blog.nil?
         # @blog = false
        #else
        #  first_post = blog.xpath('//item').first
        #  @title = first_post.xpath('title').inner_text
        #  @link = first_post.xpath('link').inner_text
        #  @content = first_post.xpath('description').inner_text.html_safe
        #  image = Nokogiri::HTML.parse(first_post.xpath('content:encoded').inner_html).css('img')
        #  if image.empty?
        #    @image = "none"
        #  else
        #    @image = image.first.attribute("src").text
        #  end 
        #end
        @title = "I am a Proud Poppa of Three Shelter Dogs"
        @link = "http://blog.shelterme.com/i-am-a-proud-poppa-of-three-shelter-dogs/".html_safe
        @content = "Do you have photos of your pets at work? Do you post pictures of them on Facebook? When you are with friends do you just have to show a photo (or three) of your pets on your phone? Then you have come to the right place. My name is Steven Latham and I am crazy about my dogs.".html_safe
        @image = "http://blog.shelterme.com/wp-content/uploads/2013/04/Steven_Dogs-300x225.jpg".html_safe
      }
    end
  rescue Timeout::Error
    @blog = false
  rescue
    @featured_pets = []
    @shelter = []
    cookies[:location] = "MapQuest not responding"
    flash[:notice] = "There are no shelters near your location."
  end
  
  def about
  end
  
  def statistics
    if !signed_in?
      redirect_to root_path
    end
    @available_pets = Pet.where(pet_state_id: 1).size
    @adopted_pets = Pet.where(pet_state_id: 2).size
    @unavailable_pets = Pet.where(pet_state_id: 3).size
    @absent_pets = Pet.where(pet_state_id: 4).size
    @fostered_pets = Pet.where(pet_state_id: 5).size
    @rescued_pets = Pet.where(pet_state_id: 6).size
    @cats = Pet.where(species_id: 1).size
    @dogs = Pet.where(species_id: 2).size
    @available_cats = Pet.where(species_id: 1, pet_state_id: 1).size
    @adopted_cats = Pet.where(species_id: 1, pet_state_id: 2).size
    @unavailable_cats = Pet.where(species_id: 1, pet_state_id: 3).size
    @absent_cats = Pet.where(species_id: 1, pet_state_id: 4).size
    @fostered_cats = Pet.where(species_id: 1, pet_state_id: 5).size
    @rescued_cats = Pet.where(species_id: 1, pet_state_id: 6).size
    @available_dogs = Pet.where(species_id: 2, pet_state_id: 1).size
    @adopted_dogs = Pet.where(species_id: 2, pet_state_id: 2).size
    @unavailable_dogs = Pet.where(species_id: 2, pet_state_id: 3).size
    @absent_dogs = Pet.where(species_id: 2, pet_state_id: 4).size
    @fostered_dogs = Pet.where(species_id: 2, pet_state_id: 5).size
    @rescued_dogs = Pet.where(species_id: 2, pet_state_id: 6).size
    @users = User.all.size
    @managers = User.where(manager: true).size
    @admins = User.where(admin: true).size
    @shelters = Shelter.all.size
    @names = Pet.all.map{|n| n.name }.inject(Hash.new(0)) {|hash, val| hash[val] += 1; hash}.entries.sort_by{|k,v| v}.reverse[0..9].select{|p| p[1] > 1}.map{|pn| pn.first}.each{|e| e}.reject{|n| n == "Name"}
    @dog_names = Pet.where(species_id: 2).map{|n| n.name }.inject(Hash.new(0)) {|hash, val| hash[val] += 1; hash}.entries.sort_by{|k,v| v}.reverse[0..9].select{|p| p[1] > 1}.map{|pn| pn.first}.each{|e| e}.reject{|n| n == "Name"}
    @cat_names = Pet.where(species_id: 1).map{|n| n.name }.inject(Hash.new(0)) {|hash, val| hash[val] += 1; hash}.entries.sort_by{|k,v| v}.reverse[0..9].select{|p| p[1] > 1}.map{|pn| pn.first}.each{|e| e}.reject{|n| n == "Name"}
    @available_journal = Shelter.all.map{|s| s.available_journal}.map{|e| e.split(",").map{|s|s.to_i}}.transpose.map{|x| x.reduce(:+)}.map{|j| j }.join ','
    @absent_journal = Shelter.all.map{|s| s.absent_journal}.map{|e| e.split(",").map{|s|s.to_i}}.transpose.map{|x| x.reduce(:+)}.map{|j| j }.join ','
    @adopted_journal = Shelter.all.map{|s| s.adopted_journal}.map{|e| e.split(",").map{|s|s.to_i}}.transpose.map{|x| x.reduce(:+)}.map{|j| j }.join ','
    @unavailable_journal = Shelter.all.map{|s| s.unavailable_journal}.map{|e| e.split(",").map{|s|s.to_i}}.transpose.map{|x| x.reduce(:+)}.map{|j| j }.join ','
    @fostered_journal = Shelter.all.map{|s| s.fostered_journal}.map{|e| e.split(",").map{|s|s.to_i}}.transpose.map{|x| x.reduce(:+)}.map{|j| j }.join ','
    @rescued_journal = Shelter.all.map{|s| s.rescued_journal}.map{|e| e.split(",").map{|s|s.to_i}}.transpose.map{|x| x.reduce(:+)}.map{|j| j }.join ','
    @shelters_state = Shelter.all.map{|n| n.state }.inject(Hash.new(0)) {|hash, val| hash[val] += 1; hash}.entries.sort_by{|k,v| v}.reverse
    @open = User.includes(:open_value).map{|u| u.open_value}.compact.inject(Hash.new(0)) {|hash, val| hash[val] += 1; hash}.entries.sort_by{|k,v| v}.last.first.name
    @plan = User.includes(:plan_value).map{|u| u.plan_value}.compact.inject(Hash.new(0)) {|hash, val| hash[val] += 1; hash}.entries.sort_by{|k,v| v}.last.first.name
    @social = User.includes(:social_value).map{|u| u.social_value}.compact.inject(Hash.new(0)) {|hash, val| hash[val] += 1; hash}.entries.sort_by{|k,v| v}.last.first.name
    @attitude = User.includes(:attitude_value).map{|u| u.attitude_value}.compact.inject(Hash.new(0)) {|hash, val| hash[val] += 1; hash}.entries.sort_by{|k,v| v}.last.first.name
    @emotion = User.includes(:emotion_value).map{|u| u.emotion_value}.compact.inject(Hash.new(0)) {|hash, val| hash[val] += 1; hash}.entries.sort_by{|k,v| v}.last.first.name

app/views/static_pages/_blog_blurb.html.erb
<div class="sidebar-element">
	<h3>
		<div class="sideIcon landingIcons blogIcon"></div>
	  <div class="landingText blogText"></div>
	</h3>
  <% unless @image == "none" %>
  <%= image_tag(@image, class: "sideImage", style:"float:right;", width: "114") %>
  <% end %>
  <div class="blurb">
    <h4><%= link_to @title, @link, target: "_blank" %></h4>
    <p><%= @content %></p>
    <%= link_to "Read more", @link, target: "_blank" %>
  </div>
  <div class="clearfix"></div>
</div>

app/views/static_pages/_events.html.erb
<div class="sidebar-element">
  <h3 style="font-weight:bold;color:#d54509;">Adoption Events</h3>
  <div class="blurb">
    <p>More than 130 pets will be available at adoption events this Saturday and Sunday, August 9th and 10th, at Pet Food Express in Rolling Hills Estates, CA.</p>
    <%= link_to "Learn more", events_path %>
  </div>
  <%= link_to image_tag("matchMeImage.png", width: "420", height: "148", style:"max-width:350px;margin-top:-4px;margin-left:-40px;margin-bottom:-35px;"), events_path %>
  <hr>
  <div class="clearfix"></div>
</div>

app/views/static_pages/_hero.html.erb
<div class="hero">
  <div id="heroCarousel" class="carousel slide" data-pause="mouseleave">
    <div class="carousel-inner">
      <div class="item active">
        <% if signed_in? %>
        <%= render "shared/hero1" %>
        <% else %>
        <%= render "shared/hero0" %>
        <% end %>
      </div>
      <div class="item">
        <% if signed_in? %>
        <%= render "shared/hero2" %>
        <% else %>
        <%= render "shared/hero1" %>
        <% end %>
      </div>
      <div class="item">
        <% if signed_in? %>
        <%= render "shared/hero3" %>
        <% else %>
        <%= render "shared/hero2" %>
        <% end %>
      </div>
      <div class="item">
        <% if signed_in? %>
        <%= render "shared/hero0" %>
        <% else %>
        <%= render "shared/hero3" %>
        <% end %>
      </div>
    </div>
    <a class="left carousel-control" href="#heroCarousel" data-slide="prev">&lsaquo;</a>
    <a class="right carousel-control" href="#heroCarousel" data-slide="next">&rsaquo;</a>
  </div>
</div>

app/views/static_pages/_tutorial_teaser.html.erb
<div class="sidebar-element">
	<h3>
		<div class="sideIcon landingIcons tutorialIcon"></div>
	  <div class="landingText tutorialText"></div>
	</h3>
  <%= link_to image_tag("tutorial.jpg", class: "tutorialTease", width: "259", height: "144"), tutorial_path %>
  <div class="clearfix"></div>
  <hr>
</div>

app/views/static_pages/events.html.erb
<% provide(:title, "Events") %>
<div class="container content">
  <div class="profile-section">
    <div class="pageHeader">
	  <div class="largeIcon shelterIcon"></div>
	  <div class="headerInfo">
	    <h1>Events</h1><br>
	    <p>(click banners below for more details &amp; lists of available pets)</p>
	  </div>
    </div>
	<div class="row" style="margin-top:20px;margin-left:0px;">
		There are no upcoming events at this time.
	</div>
  </div> 
</div>

app/views/static_pages/events_8_9.html.erb
<% provide(:title, "Events") %>
<div class="container content">
  <div class="profile-section">
    <div class="pageHeader">
	  <div class="largeIcon shelterIcon"></div>
	  <div class="headerInfo">
	    <h1>Pet Food Express</h1><br>
	    <p>27341 Hawthorne Blvd, Rolling Hills Estates, CA 90274</p>
	  	<br>
	    <p>(across from the Peninsula Shopping Center)</p>
	  </div>
	  <div class="headerButtons">
	    <%= link_to "Back to Events", events_path, {style:"float:right;padding-right:10px;"} %>
	  </div>
    </div>
    <div class="row">
      <div class="shelterDetails">
        <div class="shelterBlurb" style="height:235px;">
		  More than 100 pets from Los Angeles Country shelters will be available for adoption at the grand opening of Pet Food Express in Rolling Hills Estates.<br><br>
		  Saturday, August 9th, 10 AM - 4 PM<br><br>
		  Discounted adoption fees: $55 for dogs (normally $125) and $45 for cats (normally $115). Includes spay/neuter, microchip and vaccinations.<br><br>
		  Pet Food Express is paying the County shelters $50 for every pet they bring to the adoption event and paying an additional $100 for every pet that gets adopted, plus $100 for every pet adopted at County shelters for an entire week.
        </div>
      </div>
      <div class="rightColumn">
		<div class="map">
		  <a href="https://maps.google.com/maps?q=27341+Hawthorne+Blvd+Rolling+Hills+Estates+CA" target="_blank">
		    <img src="https://maps.googleapis.com/maps/api/staticmap?size=290x230&markers=icon:http://assets.shelterme.com/mapIcon.png|shadow:false%7Clabel:A%7C27341+Hawthorne+Blvd,Rolling+Hills+Estates,CA&zoom=14&&sensor=false&key=AIzaSyBhRhKDSxCbsS-gmm9KT6O6n_Zy6JjS8_g" width="100%" height="100%">
		  </a>
		</div>
      </div>
    </div>
  </div>  
  <div class="profile-section">
    <ul class="nav nav-tabs">
      <li>
        <a href="#dogs" data-toggle="tab">
          <span class="linkCount"></span> Dogs
        </a>
      </li>
      <li>
        <a href="#cats" data-toggle="tab">
          <span class="linkCount"></span> Cats
        </a>
      </li>
    </ul>
    <div class="possibleScroll">
      <div class="tab-content fullContent">
        <div class="tab-pane" id="dogs">
          <%= render partial: "shared/pet_tile", collection: @available_dogs, as: :f %>
          <div class="clearfix"></div>
		  <br>More profiles coming soon.
          <%= will_paginate @available_dogs, param_name: 'dogs_page' %>
        </div>
        <div class="tab-pane" id="cats">        
          <%= render partial: "shared/pet_tile", collection: @available_cats, as: :f %>
          <div class="clearfix"></div>
		  <br>More profiles coming soon.
          <%= will_paginate @available_cats, param_name: 'cats_page' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/faq.html.erb
<% provide(:title, 'FAQ') %>
<div class="container content">
  <div class="profile-section">
    <div class="row">
      <div class="rowContent">
        <div class="staticNav">
          <ul>
            <li class="active">
              <h4>FAQ</h4>
            </li>
            <li><%= link_to "About Us", about_path %></li>
            <li><%= link_to "Contact Us", contact_path %></li>
            <li><%= link_to "Terms of Use", terms_path %></li>
            <li><%= link_to "Privacy Policy", privacy_path %></li>
          </ul>
        </div>
        <div class="staticContent">
          <div class="staticEntry">
            <h3>Is ShelterMe.com available in my area?</h3>
            <div class="staticBlurb">
              <span class="answer">A</span>
              <p>Right now, the site is in public beta in Los Angeles and available only for the Los Angeles City and County animal shelters. We will be opening up the site to other municipal shelters this summer.</p>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="staticEntry">
            <a name="createProfile"></a>
            <h3>How do I create a profile of a shelter pet?</h3>
            <div class="staticBlurb">
              <span class="answer">A</span>
              <p>All you need to do is visit your local shelter, spend time with a shelter pet, take some great photos and video and write a few sentences that best describe that pet.</p>
              <p>Please write down the Animal ID number on the cage card.  It’s usually a letter followed by a series of numbers, such as:  A1278030. See the example cage card below:</p>
              <%= image_tag "baby_cageCard.jpg", style:"margin-left:auto;margin-right:auto;display:block;margin-bottom:30px;", width: "555", height: "400" %>
              <p>Then go to ShelterMe.com, create an account and click “Add Pet” on the top menu.</p>
              <p>Watch our <%= link_to "tutorial", tutorial_path %> for more information.</p>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="staticEntry">
            <h3>Can rescue organizations post their pets on ShelterMe.com?</h3>
            <div class="staticBlurb">
              <span class="answer">A</span>
              <p>No. This site is dedicated to city and county animal shelters.</p>
              <p>We define animal shelters for this site as municipal animal control agencies, run by city or county governments and private, non-profit agencies with a government contract to provide animal control services.</p>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="staticEntry">
            <h3>Who is behind ShelterMe.com?</h3>
            <div class="staticBlurb">
              <span class="answer">A</span>
              <p>This site was co-founded by Steven Latham and Ady Gil. They are the team that produces the PBS series, Shelter Me. The series celebrates shelter pets with positive and uplifting stories. The TV series raises awareness about the incredible animals at our shelters that need homes and ShelterMe.com is one of our tools to turn that awareness into action. If you ever asked, “What can I do to help our shelter pets?” there is now an answer:  create an online profile to bring more people into the shelter to help these animals get adopted.</p>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="staticEntry">
            <h3>Is ShelterMe.com a free service for animal shelters and the public?</h3>
            <div class="staticBlurb">
              <span class="answer">A</span>
              <p>Yes, totally free. The site is funded by the 501c3 foundation, <%= link_to "AGWC (Ady Gil World Conservation)", "http://agwc501.org/", target: "_blank" %>. Ady is also an executive producer of the Shelter Me TV series.</p>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="staticEntry">
            <h3>What if I try to create a profile for a pet that already has one?</h3>
            <div class="staticBlurb">
              <span class="answer">A</span>
              <p>You can contribute additional information to an existing profile. When you click “Add Pet” on the top menu bar and type in the Animal ID number from the cage card, you may get the message: Potential Match Found. If so, you can add additional photos, video and description to this profile. This can be very helpful since it creates a conversation about that animal and gives different perspectives. For example, if an animal is shy and you spend extra time with him or her, you can add to the profile so the public can see the progress. These profiles are not static or written in stone. We want to hear from multiple people and get lots of interactions with the pets.</p>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="staticEntry">
            <h3>What do I do if I see a pet that I like?</h3>
            <div class="staticBlurb">
              <span class="answer">A</span>
              <p>The great thing about the shelters is that you can go and visit the pet you see on this site any time when they're open. Click on the "Visit Me" button in the top right of the pet's profile page to see the shelter hours and address. We encourage people not to call the shelters since the people who work there are very busy.</p>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="staticEntry">
            <h3>Do you have some tips on taking good photos and video?</h3>
	          <a name="photoTips"></a>
            <div class="staticBlurb">
              <span class="answer">A</span>
              <p>The main thing is to have fun.  These pets are loving animals that need homes.  We want to make sure that the profiles make a great first impression.  Most shelters have a play area.  Please ask staff or a volunteer to take the pet out of the cage.  Here are a few simple tips:  it’s best to have the light behind you, if there are any plants, trees or home environments, please shoot photos and video with that in the background.  We want to get away from shooting through cages.</p>
							<p>If you’re with a friend or with a staff member or volunteer, have that person in the photo or video smiling.  For video, have that person describe the pet: what’s their personality like &#8230; Playful?  Energetic? Couch potato?  Do they like to play fetch? Just describe what it’s like spending time with this pet.</p>
							<p>Also, we suggest uploading a couple shorter videos (15-30 seconds) rather than one long one and keeping the video size under 4 or 5 MB.</p>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="staticEntry">
            <a name="videoTips"></a>
            <h3>Does it matter which way I hold my phone when taking video?</h3>
            <div class="staticBlurb">
              <span class="answer">A</span>
              <p>For photos and, especially, video, please hold your smartphone horizontally. A wide video is much more pleasant on the eye than a tall one. Additionally, since we display all pet photos horizontally any vertical photos that you upload must be cropped to fit.</p>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="staticEntry last">
            <h3>How many photos and video can I add?</h3>
            <div class="staticBlurb">
              <span class="answer">A</span>
              <p>You can upload as many photos and video as you’d like. Think about what you would like to see if you were looking to adopt a pet. Have the photos and video bring that pet to life…we want these profiles to inspire people to go and visit that pet right away and share that page with their friends.</p>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>