config/routes.rb
ShelterMe::Application.routes.draw do

  get "messages/new"
  get "journals/new"
  get "pet_videos/new"
  get "pet_photos/new"
  get "shelter_admins/new"
  get "favorites/new"
  get "bonds/new"
  get "addresses/new"
  get "password_resets/new"

  resources :users do
    member do
      get :following, :followers
      get :watching
      get :boosting
      get :managing
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy, :index]
  resources :relationships, only: [:create, :destroy]
  resources :password_resets
  resources :pet_photos
  resources :pet_videos
  resources :pets, except: [:create, :new, :show, :edit, :destroy]
  resources :messages, only: [:new, :create]

  resources :bonds, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :shelter_admins, only: [:create, :destroy]
  resources :breeds
  resources :searches

  root to: 'static_pages#home'
  
  match '/addphoto',          to: 'pet_photos#new'
  match '/pp',                to: 'pet_photos#index'
  
  match '/addvideo',          to: 'pet_videos#new'
  match '/pv',                to: 'pet_videos#index'
  
  match '/pc',                to: 'microposts#index'
  
  match '/s',                 to: 'shelters#index'
  match '/newshelter',        to: 'shelters#new'
  match '/findshelter',       to: 'shelters#find'
  match '/listshelters',      to: 'shelters#list'
  match '/mymanagedpets',     to: 'shelters#managed'
  match '/mmp',               to: 'shelters#managed'
  match '/:shelter_id/featured', to: 'shelters#featured'
  
  match '/p',                 to: 'pets#index'
  match '/addpet',            to: 'pets#addpet'
  match '/newpet',            to: 'pets#new'
  match '/potd',              to: 'pets#potd'
  match '/la',                to: 'pets#potd'
  
  match '/findpet',           to: 'searches#new'
  
  match '/signin',            to: 'sessions#new'
  match '/signout',           to: 'sessions#destroy', via: :delete
  
  match '/join',              to: 'users#new'
  match '/matchme',           to: 'users#matchme'
  match '/u',                 to: 'users#index'
  match '/users',             to: 'users#index'
  match '/u/:id',             to: 'users#show'
  match '/mysponsoredpets',   to: 'users#sponsored'
  match '/msp',               to: 'users#sponsored'
  match '/myfollowedpets',    to: 'users#followed'
  match '/mfp',               to: 'users#followed'
  match '/myupdates',         to: 'users#activity'
  match '/mu',                to: 'users#activity'
  match '/myfollowedusers',   to: 'users#relationships'
  match '/mfu',               to: 'users#relationships'
  match '/myphotos',          to: 'users#photos'
  match '/mp',                to: 'users#photos'
  match '/myvideos',          to: 'users#videos'
  match '/mv',                to: 'users#videos'
  match '/sm',                to: 'users#managers'
  match '/shelter_admins',    to: 'users#managers'
  
  match '/contact',           to: 'messages#new'
  match '/about',             to: 'static_pages#about'
  match '/faq',               to: 'static_pages#faq'
  match '/terms',             to: 'static_pages#terms'
  match '/privacy',           to: 'static_pages#privacy'
  match '/statistics',        to: 'static_pages#statistics'
  match '/tutorial',          to: 'static_pages#tutorial'
  match '/mobile',            to: 'static_pages#home'
  match '/events',            to: 'static_pages#events'
  match '/events_8_9',        to: 'static_pages#events_8_9'
  match '/events_8_10',       to: 'static_pages#events_8_10'

  resources :shelters, path: "", except: [:create, :new, :index, :download]
  resources :shelters, only: [:create, :new, :show, :edit, :destroy]
  resources :shelters, path: "", only: [] do
    resources :pets, path: "", only: [:create, :new, :show, :edit, :destroy]
  end
  
  match '/:shelter_id/*a',    to: "application#routing_error"
  match "*a",                 to: "application#routing_error"
  

end

app/models/pet_video.rb
# == Schema Information
#
# Table name: pet_videos
#
#  id             :integer         not null, primary key
#  pet_id         :integer
#  panda_video_id :string(255)
#  primary        :boolean         default(FALSE)
#  created_at     :datetime        not null
#  updated_at     :datetime        not null
#  user_id        :integer
#

class PetVideo < ActiveRecord::Base
  attr_accessible :panda_video_id, :pet_id, :primary, :user_id
  
  belongs_to :pet
  belongs_to :user
  
  validates :panda_video_id, presence: true, on: :create
  validates :pet_id, presence: true
  validates :user_id, presence: true
  
  default_scope order: 'pet_videos.created_at DESC'
  
  def panda_video
    @panda_video ||= Panda::Video.find(panda_video_id)
  end
  
  def h264
    @h264 = @panda_video.encodings["h264"]
  end
  
  def thumbnail
    @thumbnail = @panda_video.encodings["thumbnail"]
  end
  
end

app/controllers/pet_videos_controller.rb
class PetVideosController < ApplicationController
  before_filter :signed_in_user, only: [:create]
  
  respond_to :html, :js

  def new
    @pet = Pet.where(slug: cookies[:pet_slug]).first
    @pet_video = PetVideo.new(pet_id: @pet.id)
  rescue
    flash[:error] = "Unable to add video."
    redirect_to :back
  end

  def create
    @pet = Pet.where(slug: cookies[:pet_slug]).first
    @pet_video = PetVideo.create!(params[:pet_video])
    if @pet.pet_videos.size == 1
      @pet_video.primary = true
    end
    if @pet_video.save
      flash[:notice] = "Video of #{@pet_video.pet.name != "" ? @pet_video.pet.name : @pet_video.pet.animal_code} added."
    else
      flash[:notice] = "Upload of video failed."
      # SEND FAILED VIDEO UPLOAD ALERT EMAIL
    end   
    redirect_to [@pet.shelter, @pet] 
  rescue
    flash[:error] = "Unable to add video for #{@pet.name != "" ? @pet.name : @pet.animal_code}."
    redirect_to [@pet.shelter, @pet]
  end
  
  def edit
    @pet_video = PetVideo.find(params[:id])
  rescue
    if @pet_video
      flash[:error] = "Unable to edit video for #{@pet_video.pet.name != "" ? @pet_video.pet.name : @pet_video.pet.animal_code}."
    else
      flash[:error] = "Unable to edit video."
    end
    redirect_to :back
  end
  
  def update
    @pet_video = PetVideo.find(params[:id])
    PetVideo.where(pet_id: @pet_video.pet.id).each{|pp| pp.primary = false }.each(&:save)
    @pet_video.primary = true
    if @pet_video.update_attributes(params[:pet_video])
      flash[:notice] = "Updated the primary video for #{@pet_video.pet.name != "" ? @pet_video.pet.name : @pet_video.pet.animal_code}."
      redirect_to edit_shelter_pet_path(@pet_video.pet.shelter, @pet_video.pet)
    else
      flash[:error] = "The video of #{@pet_video.pet.name != "" ? @pet_video.pet.name : @pet_video.pet.animal_code} was not updated."
      redirect_to edit_shelter_pet_path(@pet_video.pet.shelter, @pet_video.pet)
    end
  rescue
    if @pet_video
      flash[:error] = "Unable to update video for #{@pet_video.pet.name != "" ? @pet_video.pet.name : @pet_video.pet.animal_code}."
    else
      flash[:error] = "Unable to update video."
    end
    redirect_to :back
  end
  
  def destroy
    @pet_video = PetVideo.find(params[:id])
    Panda::Video.delete(@pet_video.panda_video_id)
    @pet_video.destroy
    flash[:notice] = "Video of #{@pet_video.pet.name != "" ? @pet_video.pet.name : @pet_video.pet.animal_code} deleted."
    if cookies[:delete_media] == "true"
      redirect_to :back
      cookies[:delete_media] = "false"
    else
      redirect_to edit_shelter_pet_path(@pet_video.pet.shelter, @pet_video.pet)
    end
  rescue
    if @pet_video
      flash[:error] = "Unable to delete video for #{@pet_video.pet.name != "" ? @pet_video.pet.name : @pet_video.pet.animal_code}."
    else
      flash[:error] = "Unable to delete video."
    end
    redirect_to :back
  end

  def index
    if signed_in? && current_user.admin?
      @pet_videos = PetVideo.includes(:user, pet: :shelter).paginate(page: params[:page], per_page: 12)
    else
      redirect_to root_path
    end
  rescue
    flash[:error] = "Unable to display pet videos."
    redirect_to root_path
  end
end

app/views/pet_videos/_new.html.erb
<div id="addVideo" class="modal" data-keyboard="true">
  <div class="modal-inner mediaModal">
    <div class="pageHeader">
      <div class="largeIcon videoIcon"></div>
      <div class="headerInfo" style="width:450px;">
        <h1>Add a Video of <%= @pet.name != "" ? @pet.name : @pet.animal_code %></h1><br>
				<p></p>
      </div>
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    </div>
    <div class="form">
      <p>Horizontal videos work best. Limited to 100 MB. See <%= link_to "tips for great videos", faq_path(anchor: "videoTips"), style: "line-height:28px;font-size:12px;", target: "_blank" %>.</p>
      <div class="handhold" style="display:none;text-align:center;margin-bottom:20px;">
        This page will refresh once your upload is complete. Do not close the browser window.
      </div>
      <%= simple_form_for @pet_video do |f| %>
       <%= render 'shared/error_messages', object: f.object %>
       <%= f.hidden_field :pet_id %>
       <%= f.hidden_field :user_id, value: current_user.id %>
			<div id="file-drop" class="row filedrop" style="border:none;"> <!-- REMOVE STYLE WHEN NEW UPLOADER ADDED -->
			  <span class="btn formBtn fileinput-button" style="width:145px;margin-left:-5px;">
	        <span>Choose Video</span>
	        <input type="hidden" name="pet_video[panda_video_id]" id="returned_video_id" />
	       </span>		
         <%= image_tag("horiziPhone.png", class: "horiz", width: "110", height: "50")%>
         <p>&nbsp;&nbsp;Or drop file here <i class="icon-arrow-right"></i><i class="icon-arrow-right"></i><i class="icon-arrow-right"></i></p>
         <%= f.button :submit, "Upload", class: "formBtn" %>
       </div>
       <div id="upload_progress" class="panda_upload_progress"></div>
     <% end %>
    </div>
  </div>
</div>

<script>
  <% auth_params = Panda.signed_params('post', "/videos.json") %>
  jQuery("#returned_video_id").pandaUploader(<%=raw auth_params.to_json %>, {
    upload_progress_id: 'upload_progress'
  });

  $(function(){

		// Show selected video name
		$('input[type=file]').change(function(){
			var new_label = escape($('input[type=file]').val()).replace('C%3A%5Cfakepath%5C','');
			$('.mediaModal .headerInfo p').text(new_label);			
			if (this.files[0].size > 100000000) {
				$('.mediaModal input[type="submit"]').prop('disabled', true);
				alert("Video is too large - must be less than 100 MB.")
			} else {
				$('#new_pet_video :submit').click();
			};
		});
    
    // Hide extra video elements during upload
    $('#new_pet_video :submit').click(function(){
      $('.form p, .filedrop, button.close').hide();
      $('.mediaModal .handhold').show();
    });
    
    // Reformat progress indicator
    $('#upload_progress').css({'width':'100%','margin-bottom':'15px','margin-top':'6px'});
  });
</script>

app/views/pet_videos/_pet_videos.html.erb
<div class="pet-tile editVideo">
  <div class="tile-photo">
    <% if f.panda_video.status == "fail" %>
    <div class="processing">
      <p>Video upload failed. Please delete this and try uploading the video again.</p>
    </div>
    <% elsif f.thumbnail.status == "success" && f.h264.status == "success" %>
    <%= link_to image_tag(f.thumbnail.screenshots.first, width: "300", height: "200"), 
        [f.pet.shelter, f.pet], 
        title: "Video of #{f.pet.name != '' ? f.pet.name : f.pet.animal_code} contributed by #{f.user ? f.user.name : "Shelter Me"}" %>
    <% elsif f.thumbnail.status == "fail" or f.h264.status == "fail" %>
    <div class="processing">
      <p><%= f.thumbnail.status == "fail" ? "Thumbnail" : "Video" %> encoding failed.</p>
    </div>
    <% else %>
    <div class="processing">
     <p>Processing <%= f.thumbnail.status == "processing" ? "thumbnail..." : "video..." %><br>
      Please reload the page in a few minutes.</p>
    </div>
    <% end %>
  </div>
  <% if f.primary? %>
	  <span class="makeDefault" style="padding-top:6px;">Primary</span>
	<% else %>
    <%= simple_form_for f, html: {class: "makeDefault"} do |fp| %>
      <%= fp.submit "Make Primary" %>
    <% end %>
  <% end %>
  <%= form_for f, html: {multipart: true} do |p| %>
    <%= link_to "Delete", f, method: :delete, class: "deleteMedia", confirm: "Are you certain you want to delete this video of #{f.pet.name != '' ? f.pet.name : f.pet.animal_code}?" %>
  <% end %>
</div>

app/views/pet_videos/index.html.erb
<%= provide(:title, 'All Videos') %>
<div class="container content">
  <div class="profile-section">
    <div class="pageHeader">
      <%= render "shared/header_logo" %>
      <div class="headerInfo" style="width:385px;">
        <h1><%= pluralize(PetVideo.count, "Video") %></h1>
      </div>
    </div>
    <div id="pet_videos" class="row">
      <%= render partial: 'pet_videos', collection: @pet_videos.reverse, as: :f %>
      <div class="clearfix"></div>
      <%= will_paginate %>
    </div>
  </div>
</div>

app/views/pet_videos/new.js.erb
$('#modalTarget').html('<%= escape_javascript(render("new")) %>');
$("#addVideo").modal();