config/routes.rb
ShelterMe::Application.routes.draw do

  get "messages/new"
  get "journals/new"
  get "pet_videos/new"
  get "pet_photos/new"
  get "shelter_admins/new"
  get "favorites/new"
  get "bonds/new"
  get "addresses/new"
  get "password_resets/new"

  resources :users do
    member do
      get :following, :followers
      get :watching
      get :boosting
      get :managing
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy, :index]
  resources :relationships, only: [:create, :destroy]
  resources :password_resets
  resources :pet_photos
  resources :pet_videos
  resources :pets, except: [:create, :new, :show, :edit, :destroy]
  resources :messages, only: [:new, :create]

  resources :bonds, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :shelter_admins, only: [:create, :destroy]
  resources :breeds
  resources :searches

  root to: 'static_pages#home'
  
  match '/addphoto',          to: 'pet_photos#new'
  match '/pp',                to: 'pet_photos#index'
  
  match '/addvideo',          to: 'pet_videos#new'
  match '/pv',                to: 'pet_videos#index'
  
  match '/pc',                to: 'microposts#index'
  
  match '/s',                 to: 'shelters#index'
  match '/newshelter',        to: 'shelters#new'
  match '/findshelter',       to: 'shelters#find'
  match '/listshelters',      to: 'shelters#list'
  match '/mymanagedpets',     to: 'shelters#managed'
  match '/mmp',               to: 'shelters#managed'
  match '/:shelter_id/featured', to: 'shelters#featured'
  
  match '/p',                 to: 'pets#index'
  match '/addpet',            to: 'pets#addpet'
  match '/newpet',            to: 'pets#new'
  match '/potd',              to: 'pets#potd'
  match '/la',                to: 'pets#potd'
  
  match '/findpet',           to: 'searches#new'
  
  match '/signin',            to: 'sessions#new'
  match '/signout',           to: 'sessions#destroy', via: :delete
  
  match '/join',              to: 'users#new'
  match '/matchme',           to: 'users#matchme'
  match '/u',                 to: 'users#index'
  match '/users',             to: 'users#index'
  match '/u/:id',             to: 'users#show'
  match '/mysponsoredpets',   to: 'users#sponsored'
  match '/msp',               to: 'users#sponsored'
  match '/myfollowedpets',    to: 'users#followed'
  match '/mfp',               to: 'users#followed'
  match '/myupdates',         to: 'users#activity'
  match '/mu',                to: 'users#activity'
  match '/myfollowedusers',   to: 'users#relationships'
  match '/mfu',               to: 'users#relationships'
  match '/myphotos',          to: 'users#photos'
  match '/mp',                to: 'users#photos'
  match '/myvideos',          to: 'users#videos'
  match '/mv',                to: 'users#videos'
  match '/sm',                to: 'users#managers'
  match '/shelter_admins',    to: 'users#managers'
  
  match '/contact',           to: 'messages#new'
  match '/about',             to: 'static_pages#about'
  match '/faq',               to: 'static_pages#faq'
  match '/terms',             to: 'static_pages#terms'
  match '/privacy',           to: 'static_pages#privacy'
  match '/statistics',        to: 'static_pages#statistics'
  match '/tutorial',          to: 'static_pages#tutorial'
  match '/mobile',            to: 'static_pages#home'
  match '/events',            to: 'static_pages#events'
  match '/events_8_9',        to: 'static_pages#events_8_9'
  match '/events_8_10',       to: 'static_pages#events_8_10'

  resources :shelters, path: "", except: [:create, :new, :index, :download]
  resources :shelters, only: [:create, :new, :show, :edit, :destroy]
  resources :shelters, path: "", only: [] do
    resources :pets, path: "", only: [:create, :new, :show, :edit, :destroy]
  end
  
  match '/:shelter_id/*a',    to: "application#routing_error"
  match "*a",                 to: "application#routing_error"
  

end

app/views/shared/_delete_link.html.erb
<% if current_user?(object.user) or (signed_in? and current_user.admin?) %>
  <%= link_to "Delete", object, method:  :delete,
                                confirm: "Are you sure you want to delete this comment?" %>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <div class="innerComment">
    <div class="avatar">
    <% if feed_item.user %>
    <%= link_to avatar_for(feed_item.user), feed_item.user %>
    <% else %>
    <%= image_tag "silhouette.png", class: "avatar", width: "40", height: "40" %>
    <% end %>
    </div>
    <div class="post wide">
      <% if signed_in? and feed_item.user == current_user %> 
        <%= link_to "You", feed_item.user %>
        <span class="action"><%= ["are awesome", "rock", "are wonderful", "are amazing", "are incredible", "are terrific"][Random.rand(0..5)] %></span>
      <% else %>
        <% if feed_item.user %>
        <%= link_to feed_item.user.name, feed_item.user %>
        <% else %>
        <span style="font-weight:bold;">Shelter Me</span>
        <% end %>
      <% end %> 
      <span class="time"><%= time_ago_in_words(feed_item.created_at) %></span>
      <p><%= wrap(feed_item.content) %></p>
      <%= render 'shared/delete_link', object: feed_item %>
    </div>
  </div>
</li>

app/views/shared/_header_logo.html.erb
<div class="largeIcon <%= params[:controller] == 'pets' ? (params[:action] == 'show' ? (@pet.species.name == 'dog' ? 'dogIcon' : 'catIcon') : 'dogIcon') : (params[:controller] == 'shelters' ? 'shelterIcon' : (params[:controller] == 'users' ? 'editProfileIcon' : (params[:controller] == 'microposts' ? 'editIcon' : (params[:controller] == 'pet_photos' ? 'photoIcon' : (params[:controller] == 'pet_videos' || (params[:controller] == 'static_pages' && params[:action] == 'tutorial') ? 'videoIcon' : ''))))) %>">
	<% if params[:controller] == 'users' and params[:action] == 'show' %>
	  <%= avatar_for @user, size: 63 %>
	<% end %>
</div>

app/views/shared/_hero0.html.erb
<div class="container">
  <div class="heroBlurb" style="width:540px;">
    <h2><%= image_tag("theSocialNetwork.png", width: "499", height: "26") %></h2>
    <p>There are millions of pets in our shelters waiting for homes and they need your help! Even if you're not looking to adopt, you can give shelter pets an online presence and help them find a home.</p>
    <div class="smallCat">
      <%= image_tag("smallHeroCat.png", width: "300", height: "106") %>
    </div>
    <p>Our goal is to increase the visibility of shelter pets. Do you have some basic Internet skills? You can help!</p><br>
    <p><a href="#heroCarousel" data-slide="next">Learn more</a></p>
  </div>
  <div class="heroContent heroLogo">
    <%= image_tag("logoHero.png", width: "395", height: "200") %>
  </div>
</div> 

app/views/shared/_hero2.html.erb
<div class="container">
  <div class="heroBlurb">
    <h2><%= image_tag("helpAShelterPet.png", width: "436", height: "32")%></h2>
    <p>You can make a difference by visiting your local shelter and creating pet profiles so others in your area can see all of the incredible pets waiting to be adopted. This can help just as much as adopting a pet, volunteering your time or making a financial contribution.</p><br>
    <%= image_tag("logo.png", alt: "Shelter Me", class: "logo-large", width: "141", height: "72") %>
    <p>Visit a shelter, interact with the pets, take a few photos, shoot a video or two, and then add a profile using our <%= link_to "Add Pet", addpet_path %> functionality.</p><br>
    <p>Visit your <%= link_to "local shelter", findshelter_path %> today!</p>
  </div>
  <div class="heroContent heroCat">
    <%= image_tag("heroCat.png", width: "249", height: "265") %>
  </div>
</div>  

app/views/shared/_hero3.html.erb
<div class="container">
  <div class="heroBlurb" style="width:480px;">
    <h2><%= image_tag("tvSeries.png", width: "287", height: "26")%></h2>
    <p>This PBS series is about redemption, hope, helping others and making a difference. It tells positive and uplifting stories about shelter pets improving the lives of those who connect with them.</p><br>
    <%= image_tag("logo.png", alt: "Shelter Me", class: "logo-large", width: "141", height: "72") %>
    <p>The second episode is currently airing on PBS throughout the country.</p><br><br>
    <a href="http://www.shelterme.tv" target="_blank" style="font-size:14px;">Learn more about the show</a>
  </div>
  <div class="heroContent heroVideo">
    <iframe width="436" height="245" src="http://www.youtube.com/embed/E6qcMrr5L_M?rel=0" frameborder="0" allowfullscreen></iframe>
  </div>
</div>

app/views/shared/_history_tile.html.erb
<li class="small-pet-tile <%= f.pet_state.status %>">
  <div class="small-tile-photo">
    <% if f.pet_photos.where(primary: true).size > 0 %>
      <%= link_to image_tag(f.pet_photos.where(primary: true).first.image_url.to_s.gsub!(/upload/,"upload/t_history"), width: "135", height: "90"), [f.shelter, f], target: "#{params[:controller] == 'searches' or (params[:controller] == 'users' and params[:action] == 'matchme') ? "_blank" : "_self"}" %>
    <% elsif f.pet_photos.size > 0 %>
      <%= link_to image_tag(f.pet_photos.first.image_url.to_s.gsub!(/upload/,"upload/t_history"), width: "135", height: "90"), [f.shelter, f], target: "#{params[:controller] == 'searches' or (params[:controller] == 'users' and params[:action] == 'matchme') ? "_blank" : "_self"}" %>
    <% else %>
      <%= link_to "", [f.shelter, f], target: "#{params[:controller] == 'searches' or (params[:controller] == 'users' and params[:action] == 'matchme') ? "_blank" : "_self"}" %>
    <% end %>
	  <% if f.pet_state.status == 'available' || f.pet_state.status == 'absent' %>
	  <% if f.intake_date %>
	  <div class="corner noPrint <%= f.intake_date < 1.month.ago ? 'veteran' : ( f.intake_date < 1.week.ago ? 'middle' : 'new' ) %>Intake">
			<%= link_to "#{f.days_in_shelter}", "#", rel: "tooltip", title: "Has been at the shelter for #{f.days_in_shelter} days" %>
		</div>
	  <% else %>
	  <div class="corner <%= f.created_at < 1.month.ago ? 'veteran' : ( f.created_at < 1.week.ago ? 'middle' : 'new' ) %>Addition">
			<%= link_to "", [f.shelter, f], rel: "tooltip", title: "#{f.created_at < 1.month.ago ? 'Added more than a month ago' : ( f.created_at < 1.week.ago ? 'Added in the last month' : 'Newly added' )}" %>
		</div>
		<% end %>
	  <% end %>
	  <% if f.pet_state.status != 'available' %>
    <div class="<%= f.pet_state.status == 'adopted' ? 'smallIcon adoptedIcon' : (f.pet_state.status == 'absent' ? 'smallIcon absentIcon' : (f.pet_state.status == 'fostered' ? 'smallIcon fosteredIcon' : 'smallIcon rescuedIcon'))%>">
	    <%= link_to "", [f.shelter, f], rel: "tooltip", title: "#{f.pet_state.status == 'adopted' ? 'Adopted' : (f.pet_state.status == 'absent' ? 'May not be available' : (f.pet_state.status == 'fostered' ? 'Being fostered' : 'With a rescue'))}" %>
	  </div>
	  <% end %>
  </div>
  <div class="small-pet-info">
    <h3>
      <% if f.name != "" %>
      <%= link_to f.name, [f.shelter, f], target: "#{params[:controller] == 'searches' or (params[:controller] == 'users' and params[:action] == 'matchme') ? "_blank" : "_self"}" %>
      <% else %>
      <%= link_to f.animal_code, [f.shelter, f], target: "#{params[:controller] == 'searches' or (params[:controller] == 'users' and params[:action] == 'matchme') ? "_blank" : "_self"}" %>
      <% end %>
    </h3>
    <p>
      <span class="breed-tile">
        <% if f.secondary_breed == nil %>
          <%= f.primary_breed.name %>
        <% else %>
          <%= f.primary_breed.name %> / <%= f.secondary_breed.name %>
        <% end %>
      </span>
      <br>
      <% if f.pet_state.status == 'fostered' || f.pet_state.status == 'rescued' %>
	    <% if f.refuge_name.present? %>
	    <span style="font-weight:bold;"><%= f.pet_state.status == 'fostered' ? 'Being fostered by ' : 'With '%><%= f.refuge_name %></span>
	    <% else %>
	    <span style="font-weight:bold;"><%= f.pet_state.status == 'fostered' ? 'Being fostered' : 'With a rescue'%></span>
	    <% end %>
      <% else %>
      <%= link_to f.shelter.name, f.shelter, class: "shelter-tile", target: "#{params[:controller] == 'searches' or (params[:controller] == 'users' and params[:action] == 'matchme') ? "_blank" : "_self"}" %>
      <% end %>
    </p>
  </div>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div>
    <% pet_id = @pet.id %>
    <%= f.hidden_field :pet_id %>
  </div>
  <div class="field">
    <%= f.text_area :content, placeholder: "Share your thoughts...", style: "margin-bottom: 15px;" %>
  </div>
  <div id="char_count" class="comment"></div>
  <div class="clearfix"></div>
  <%= f.submit "Comment", class: "btn btn-header", style: "width: 117px; height: 28px;" %>
<% end %>

app/views/shared/_pet_tile.html.erb
<div class="pet-tile <%= f.pet_state.status %>">
  <div class="tile-photo">
    <% if f.pet_photos.where(primary: true).size > 0 %>
      <%= link_to image_tag(f.pet_photos.where(primary: true).first.image_url.to_s.gsub!(/upload/,"upload/t_tile"), width: "300", height: "200"), [f.shelter, f], target: "#{params[:controller] == 'searches' or (params[:controller] == 'users' and params[:action] == 'update') ? "_blank" : "_self"}" %>
    <% elsif f.pet_photos.size > 0 %>
      <%= link_to image_tag(f.pet_photos.first.image_url.to_s.gsub!(/upload/,"upload/t_tile"), width: "300", height: "200"), [f.shelter, f], target: "#{params[:controller] == 'searches' or (params[:controller] == 'users' and params[:action] == 'update') ? "_blank" : "_self"}" %>
    <% else %>
      <%= link_to "Please add a photo", [f.shelter, f], target: "#{params[:controller] == 'searches' or (params[:controller] == 'users' and params[:action] == 'update') ? "_blank" : "_self"}", style: "text-align:center;padding-top:30px;" %>
    <% end %>
    <% if f.pet_state.status == 'available' || f.pet_state.status == 'absent' %>
    <% if f.intake_date %>
    <div class="corner noPrint <%= f.intake_date < 1.month.ago ? 'veteran' : ( f.intake_date < 1.week.ago ? 'middle' : 'new' ) %>Intake">
      <%= link_to "#{f.days_in_shelter}", "#", rel: "tooltip", title: "Has been at the shelter for #{f.days_in_shelter} days" %>
    </div>
    <% else %>
    <div class="corner <%= f.created_at < 1.month.ago ? 'veteran' : ( f.created_at < 1.week.ago ? 'middle' : 'new' ) %>Addition">
      <%= link_to "", [f.shelter, f], rel: "tooltip", title: "#{f.created_at < 1.month.ago ? 'Added more than a month ago' : ( f.created_at < 1.week.ago ? 'Added in the last month' : 'Newly added' )}" %>
    </div>
    <% end %>
    <% end %>
    <% if f.pet_state.status != 'available' %>
    <div class="<%= f.pet_state.status == 'adopted' ? 'mediumIcon adoptedIcon' : (f.pet_state.status == 'absent' ? 'mediumIcon absentIcon' : (f.pet_state.status == 'unavailable' ? 'mediumIcon unavailableIcon' : (f.pet_state.status == 'fostered' ? 'mediumIcon fosteredIcon' : 'mediumIcon rescuedIcon')))%>">
      <%= link_to "", [f.shelter, f], rel: "tooltip", title: "#{f.pet_state.status == 'adopted' ? 'Adopted' : (f.pet_state.status == 'absent' ? 'May not be available' : (f.pet_state.status == 'fostered' ? 'Being fostered' : (f.pet_state.status == 'rescued' ? 'With a rescue' : 'Unavailable')))}" %>
    </div>
    <% end %>
  </div>
  <div class="pet-icons">
    <ul>
      <li><%= render 'shared/icons/ageGender', f: f %></li>
      <li><%= render 'shared/icons/sizeWeight', f: f %></li>
      <li><%= render 'shared/icons/color', f: f %></li>
      <li><%= render 'shared/icons/energy', f: f %></li>
      <li><%= render 'shared/icons/nature', f: f %></li>
      <li><%= render 'shared/icons/affection', f: f %></li>
    </ul>
  </div> 
  <div class="pet-name">
    <h3>
      <% if f.name != '' %>
        <%= link_to f.name, [f.shelter, f], target: "#{params[:controller] == 'searches' or (params[:controller] == 'users' and params[:action] == 'update') ? "_blank" : "_self"}", class: "animal_name" %>
        <%= link_to f.animal_code, [f.shelter, f], target: "#{params[:controller] == 'searches' or (params[:controller] == 'users' and params[:action] == 'update') ? "_blank" : "_self"}", class: "animal_code" %>
      <% else %>
        <%= link_to f.animal_code, [f.shelter, f], target: "#{params[:controller] == 'searches' or (params[:controller] == 'users' and params[:action] == 'update') ? "_blank" : "_self"}" %>
      <% end %>
    </h3>
  </div>
  <div class="pet-info">
    <p style="color:gray;">
      <% if f.secondary_breed == nil %>
        <%= f.primary_breed.name %>
      <% else %>
        <%= f.primary_breed.name %> / <%= f.secondary_breed.name %>
      <% end %>
    </p>
    <p>
      <% if f.pet_state.status == 'fostered' || f.pet_state.status == 'rescued' %>
      <% if f.refuge_name.present? %>
      <span style="font-weight:bold;"><%= f.pet_state.status == 'fostered' ? 'Being fostered by ' : 'With '%><%= f.refuge_name %></span>
      <% else %>
      <span style="font-weight:bold;"><%= f.pet_state.status == 'fostered' ? 'Being fostered' : 'With a rescue'%></span>
      <% end %>
      <% else %>
      <%= link_to f.shelter.name, f.shelter, class: "shelter-tile", target: "#{params[:controller] == 'searches' or (params[:controller] == 'users' and params[:action] == 'matchme') ? "_blank" : "_self"}" %>
      <% end %>
    </p>
  </div>
  <div class="pet-state">
    <span class="commentCount"><%= link_to f.bonds_count, "#", rel: "tooltip", title: pluralize(f.bonds_count.to_s, " follower"), class: "unlink" %></span>
  </div>
</div>

app/views/shared/_signed_in.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <%= render 'shared/user_info' %>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
    <section>
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
<div class="span8">
  <h3>Micropost Feed</h3>
  <%= render 'shared/feed' %>
</div>
</div>  

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_thin_map.html.erb
<a href="https://maps.google.com/maps?q=<%=s.street.gsub(/ /,'+')%>+<%=s.city.gsub(/ /,'+')%>,<%=s.state%>" target="_blank">
  <img src="https://maps.googleapis.com/maps/api/staticmap?size=304x104&markers=icon:http://assets.shelterme.com/1pxBlank.png|shadow:false%7C<%=s.street.gsub(/ /,'+')%>+<%=s.city.gsub(/ /,'+')%>,<%=s.state%>&zoom=13&&sensor=false&key=AIzaSyBhRhKDSxCbsS-gmm9KT6O6n_Zy6JjS8_g">
</a>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= avatar_for current_user, size: 50 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>